### ISSUE TITLE
Tests do not run

### ISSUE THREAD

**Issue by joebochill** [etn-ccis/blui-react-native-showcase-demo#12]
#### Describe the desired behavior
Tests should run and pass.

#### Describe the current behavior
Tests do not execute properly.

#### Is this request related to a current issue?
No

#### Additional Context

Appears to be some sort of configuration issue with babel or jest or an incompatibility of some versions of some of the packages perhaps.

**Comment by joebochill** [comment]
I fixed something similar to this in the workflows demo and all of the projects that were scaffolded by the CLI (there was some missing jest configuration that caused the tests to fail). I suspect if we re-scaffold this with the updated CLI, this issue should go away (or we can look at the recent changes in the CLI/templates and replicate the configuration changes here).

**Comment by huayunh** [comment]
It runs
